Repository CSUEB-Black-Jack-Group-5/CS401-BlackJack-Implementation, pull requests merged in 2025-05, with the labels that each got.

#22 create database folder and file structure
  res/db/Players/marting99/marting99.csv
  res/db/Players/marting99/marting99_history.csv
  res/db/allDealers.csv
  res/db/allPlayers/allPlayers.csv
  res/db/allPlayers/allPlayersHistory.csv
  src/dbHelper/CSVDatabaseHelper.java
Labels: enhancement

#48 TestGuiFrame: Mocked the deal request message.
  src/client/test_gui/TestGuiFrame.java
Labels: bug fix

#46 Updated DealerClientThread
  src/server/DealerClientThread.java
Labels: bug fix

#49 missed this during review🤦‍♂️
  src/server/DealerClientThread.java
Labels: bug fix

#50 also missed these changes during review. removed IDs
  res/db/Players/marting99/marting99.csv
  res/db/allPlayers/allPlayersHistory.csv
Labels: bug fix

#26 Split: Initial proposal for splitting functionality
  src/game/CardHand.java
  src/game/Player.java
Labels: enhancement

#55 Feature login
  res/db/Players/marting99/marting99.csv
  res/db/allPlayers/allPlayers.csv
  src/client/BlackjackGame.java
  src/client/ClientMain.java
  src/client/gui/BlackjackIntroGUI.java
  src/client/gui/LoginGUI.java
  src/dbHelper/CSVDatabaseHelper.java
  src/server/Server.java
Labels: enhancement

#42 Update Player and Dealer Lobby and connect Login to Lobby
  src/client/BlackjackGame.java
  src/client/DealerLobbyGUI/DealerLobbyBlackJack.java
  src/client/DealerLobbyGUI/DealerLobbyBlackJackPanel.java
  src/client/DealerLobbyGUI/GoldBorderDealerLobby.java
  src/client/DealerLobbyGUI/RoundedButtonDealerLobby.java
  src/client/DealerLobbyGUI/RoundedPanelDealerLobby.java
  src/client/PlayerLobbyGUI/GoldBorderPlayerLobby.java
  src/client/PlayerLobbyGUI/PlayerLobbyBlackJack.java
  src/client/PlayerLobbyGUI/PlayerLobbyBlackJackPanel.java
  src/client/PlayerLobbyGUI/RoundedButtonPlayerLobby.java
  src/client/PlayerLobbyGUI/RoundedPanelPlayerLobby.java
  src/client/gui/BlackJackMainGUI.java
  src/client/gui/BlackjackIntroGUI.java
  src/client/gui/LoginGUI.java
Labels: attention needed

#27 ValueTests: Initial test setup for the value class.
  src/tests/ValueTests.java
Labels: test

#28 SuitTests: Initial test setup for suit class.
  src/tests/SuitTests.java
Labels: test

#29 CardTests: Initial test setup for card class.
  src/game/Card.java
  src/tests/CardTests.java
Labels: test

#23 WalletTests: Implemented what I think is a good start on wallet testing
  src/game/Wallet.java
  src/tests/WalletTests.java
Labels: test

#30 TimerTests: Initial test setup for the Timer class.
  src/game/Timer.java
  src/tests/TimerTests.java
Labels: test

#72 Implemented Table Data Requests and Responses
  src/client/BlackjackGame.java
  src/client/DealerLobbyGUI/DealerLobbyBlackJackPanel.java
  src/client/DealerTable/DealerTableBlackJack.java
  src/client/PlayerTable/PlayerTableBlackJack.java
  src/client/test_gui/TestGuiFrame.java
  src/game/Lobby.java
  src/game/Table.java
  src/networking/Message.java
  src/server/DealerClientThread.java
  src/server/PlayerClientThread.java
  src/server/Server.java
  src/server/TableThread.java
  src/tests/TableTests.java
Labels: attention needed

#76 Updated PR #64 CardHandTest to JUnit 4.13
  src/tests/CardHandTest.java
Labels: test
